### ISSUE TITLE
VM Provisioning Error 

### ISSUE THREAD

**Issue by EngASaaid** [itnetxbe/VMRoles#1]
Error (31304)
VM Role resource (SQL1234) was not successfully deployed in the Cloud Service. 

Recommended Action
VM Role can be repaired if the entity was created.

Error (23776)
The VM [SQL4321.] could not be placed on cloud [AHQ Prod] due to the following issues: 

(8 / 8) 23771
The virtual machine SQL4321. requires local storage and the most appropriate available destination volume connected to host AHQHVPROD08 is not a local storage device.

Recommended Action
Ensure that there are no operations occurring on virtual machine SQL4321. and attempt placement again.

Error (23737)
The deployment configuration for VM with name SQL4321. cannot be placed on the host group or cloud that it targets. More detailed information can be found by getting star ratings for the target host group or cloud.

Recommended Action
Ensure that sufficient host resources are available on the host group or cloud that this virtual machine configuration targets by resolving any issues found while rating the virtual machine and try the operation again.

Error (23737)
The deployment configuration for VM with name SQL4321. cannot be placed on the host group or cloud that it targets. More detailed information can be found by getting star ratings for the target host group or cloud.

Recommended Action
Ensure that sufficient host resources are available on the host group or cloud that this virtual machine configuration targets by resolving any issues found while rating the virtual machine and try the operation again.

Error (22042)
The service SQL1234 was not successfully deployed. Review the event log to determine the cause and corrective actions.

Recommended Action
The deployment can be restarted by retrying the job.

Information (22598)
The computer tier template contains a virtual machine template with a hard-coded computer name. If patterns are not used, the tier cannot be scaled out.

Error (31304)
VM Role resource (SQL1234) was not successfully deployed in the Cloud Service. 

Recommended Action
VM Role can be repaired if the entity was created.

Error (23776)
The VM [SQL4321. ] could not be placed on cloud [AHQ Prod] due to the following issues: 

(8 / 8) 23771
The virtual machine SQL4321.  requires local storage and the most appropriate available destination volume connected to host AHQHVPROD08 is not a local storage device.

Recommended Action
Ensure that there are no operations occurring on virtual machine SQL4321.  and attempt placement again.

Error (23737)
The deployment configuration for VM with name SQL4321.  cannot be placed on the host group or cloud that it targets. More detailed information can be found by getting star ratings for the target host group or cloud.

Recommended Action
Ensure that sufficient host resources are available on the host group or cloud that this virtual machine configuration targets by resolving any issues found while rating the virtual machine and try the operation again.

Error (23737)
The deployment configuration for VM with name SQL4321.  cannot be placed on the host group or cloud that it targets. More detailed information can be found by getting star ratings for the target host group or cloud.

Recommended Action
Ensure that sufficient host resources are available on the host group or cloud that this virtual machine configuration targets by resolving any issues found while rating the virtual machine and try the operation again.

Error (22042)
The service SQL1234 was not successfully deployed. Review the event log to determine the cause and corrective actions.

Recommended Action
The deployment can be restarted by retrying the job.

Information (22598)
The computer tier template contains a virtual machine template with a hard-coded computer name. If patterns are not used, the tier cannot be scaled out.

[Errorr SQL 2016 .txt](https://github.com/itnetxbe/VMRoles/files/1144588/Errorr.SQL.2016.txt)

**Comment by bgelens** [comment]
Closing this as it is not an issue with the VM Role but with your Azure Pack setup.
My best guess is you are targeting a Hyper-V cluster and don't have the SCVMM Cloud custom property set correctly.
Please check your cloud **AHQ Prod** custom properties. It should contain a custom property called ```CreateHighlyAvailableVmRoles``` and have the value set to ```true``` in case of Hyper-V clusters. If it does not exists, you need to create it manualy.

**Comment by EngASaaid** [comment]
thanks for your reply, 
but the custom property already created. i created it manually before adding the VM Role.

**Comment by bgelens** [comment]
You need to figure out this error:
>>The virtual machine SQL4321.adnoc.co.ae requires local storage and the most appropriate available destination volume connected to host AHQHVPROD08 is not a local storage device.

Keeping it closed as it doesn't relate to the actual Gallery Item itself

**Comment by EngASaaid** [comment]
yes, it is remote storage, in this case there are no solution? 
**in this case i **can not** use any Vm role gallery?**

**Comment by bgelens** [comment]
could you post a screen capture of your cloud custom properties?

**Comment by EngASaaid** [comment]
![capture](https://user-images.githubusercontent.com/30144180/28401119-cb80fd64-6d28-11e7-8152-8077a9ae8e8c.PNG)

**Comment by bgelens** [comment]
Looking good. Not sure if it will help you with this but you could try to add ```DifferencingDiskOptimizationSupported``` and set it to ```false``` to make sure you are not having issues with placement of the "Parent" disk.

**Comment by EngASaaid** [comment]
i faced the same issue.

**Comment by bgelens** [comment]
I would suggest posting your issue in the [MSDN forums](https://social.msdn.microsoft.com/Forums/azure/en-US/home?forum=windowsazurepack&filter=alltypes&sort=lastpostdesc) for Azure Pack.
